name: GitHub Profile 3D Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: 3D katkı grafiği üret
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: mustafa-php

      - name: Değişiklikleri gönder
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "3D contribution chart güncellendi"
